version: '3'
services:
  cms:
    image: cms
    build:
      context: ./cms
    environment:
      API_HOST: http://localhost:8001/api
    ports:
      - 81:80
#    depends_on:
#      - server
  lk:
    image: ui
    build:
      context: ./provider-ui
    environment:
      API_HOST: http://localhost:8001/api
    ports:
      - 80:80
    depends_on:
      - server
  server:
    build:
      context: ./provider-back
    environment:
      POSTGRES_HOST: postgres
      TOKEN_KEY: mytokenstring
      POSTGRES_DB: provider
    ports:
      - 8001:8001
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_PASSWORD=Initial0
    volumes:
      - pg5:/var/lib/postgresql/data
      - ./provider-back/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432


volumes:
  pg5:
